name: Run JMeter Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Java (JMeter butuh Java)
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Install JMeter
      - name: Install Apache JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      # 4. Create reports folder
      - name: Create reports folder
        run: mkdir -p reports

      # 5. Run JMeter test
      - name: Run JMeter test
        run: |
          jmeter/bin/jmeter -n -t load-test.jmx -l reports/result.jtl

      # 6. Upload JMeter results as artifact
      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: reports/
